name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
        INSTALLATION_ROOT: ./
              
    - name: install dependencies
      run: sudo apt-get install build-essential gcc git qt5-default qt5-qmake
      
    - name: build
      run: cd sqlparser && sh ./build_all64.sh
              
    # prepare artifact
    # - name: Prepare artifact
    #   run: tar -cvzf ${{ github.workspace }}/sqlines ${{ github.workspace }}/pgmodeler/build/

    # upload artifact
    # - uses: actions/upload-artifact@v2-preview
    #   with:
    #     name: pgmodeler
    #     path: ${{ github.workspace }}/pgmodeler-dist.tar.gz
      
